// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.24.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

CustomType create({dynamic hint}) => RustLib.instance.api.create(hint: hint);

class CustomType {
  final String name;

  const CustomType({
    required this.name,
  });

  static CustomType newCustomType({required String name, dynamic hint}) =>
      RustLib.instance.api.customTypeNew(name: name, hint: hint);

  @override
  int get hashCode => name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomType &&
          runtimeType == other.runtimeType &&
          name == other.name;
}
